name: face-attendance-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch
      - torchvision
      - boto3
      - numpy
      - python-dotenv
      - fastapi
      - ultralytics
      - uvicorn
      - opencv-python-headless
      - Pillow
      - python-multipart
      - git+https://github.com/wiktorlazarski/head-segmentation.git
